In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
rootPath = "../../../../../"
dataset=pd.read_csv(rootPath+"Datasets/CKD.csv")
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...      False        False       False   
1    137.528754  4.627244  10.700000  ...       True        False       False   
2    138.000000  4.400000  12.000000  ...       True        False       False   
3    138.000000  3.200000   8.100000  ...       True        False       False   
4    137.528754  4.627244  11.800000  ...       True        False       False   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...       True        False       False   
395  137.528754  4.627244   8.700000  ...       True        False       False   
396  134.000000  2.700000   9.100000  ...       True        False       False   
397  142.000000  5.500000   8.500000  ...       True        False       False   
398  140.000000  5.000000  16.300000  ...       True        False       False   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0      False   False    False       True    True    False                True  
1      False   False    False       True   False    False                True  
2      False   False    False       True   False    False                True  
3      False   False    False       True   False     True                True  
4      False   False    False       True   False    False                True  
..       ...     ...      ...        ...     ...      ...                 ...  
394    False   False    False       True   False    False                True  
395     True    True    False       True   False     True                True  
396     True    True    False      False   False    False                True  
397     True    True    False       True   False     True                True  
398    False   False    False       True   False    False               False  

[399 rows x 28 columns]

In [18]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [19]:
dataset["classification_yes"].value_counts()

classification_yes
True     249
False    150
Name: count, dtype: int64

In [20]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dependent=dataset["classification_yes"]

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [22]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import RidgeClassifier
param_grid={'solver':['cholesky','auto'],'class_weight':['balanced']}#'alpha':['2'],'fit_intercept':['True'],
grid=GridSearchCV(RidgeClassifier(),param_grid,refit=True,verbose=3,n_jobs=1)
grid.fit(X_train,y_train)

Fitting 5 folds for each of 2 candidates, totalling 10 fits
[CV 1/5] END class_weight=balanced, solver=cholesky;, score=0.946 total time=   0.0s
[CV 2/5] END class_weight=balanced, solver=cholesky;, score=0.964 total time=   0.0s
[CV 3/5] END class_weight=balanced, solver=cholesky;, score=0.875 total time=   0.0s
[CV 4/5] END class_weight=balanced, solver=cholesky;, score=0.946 total time=   0.0s
[CV 5/5] END class_weight=balanced, solver=cholesky;, score=0.945 total time=   0.0s
[CV 1/5] END class_weight=balanced, solver=auto;, score=0.946 total time=   0.0s
[CV 2/5] END class_weight=balanced, solver=auto;, score=0.964 total time=   0.0s
[CV 3/5] END class_weight=balanced, solver=auto;, score=0.875 total time=   0.0s
[CV 4/5] END class_weight=balanced, solver=auto;, score=0.946 total time=   0.0s
[CV 5/5] END class_weight=balanced, solver=auto;, score=0.945 total time=   0.0s


GridSearchCV(estimator=RidgeClassifier(), n_jobs=1,
             param_grid={'class_weight': ['balanced'],
                         'solver': ['cholesky', 'auto']},
             verbose=3)

In [23]:
y_pred=grid.predict(X_test)
y_pred

array([False,  True, False,  True,  True,  True,  True,  True, False,
       False,  True,  True, False,  True, False, False,  True, False,
        True,  True, False,  True,  True, False,  True, False, False,
       False,  True,  True,  True,  True, False, False, False, False,
       False, False,  True, False, False,  True, False,  True,  True,
        True, False, False, False,  True,  True,  True,  True, False,
        True,  True, False,  True, False, False, False,  True,  True,
        True,  True,  True, False,  True, False,  True, False,  True,
       False, False, False,  True,  True,  True,  True, False,  True,
        True, False, False,  True,  True, False,  True, False,  True,
        True,  True, False, False,  True,  True,  True,  True,  True,
        True,  True, False, False,  True, False,  True, False,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
       False, False, False])

In [24]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[45,  0],
       [ 8, 67]], dtype=int64)

In [25]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)

In [26]:
print(clf_report)

              precision    recall  f1-score   support

       False       0.85      1.00      0.92        45
        True       1.00      0.89      0.94        75

    accuracy                           0.93       120
   macro avg       0.92      0.95      0.93       120
weighted avg       0.94      0.93      0.93       120



In [27]:
re=grid.cv_results_
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.007380      0.000798         0.005585        0.003253   
1       0.012317      0.004356         0.004302        0.001735   

  param_class_weight param_solver  \
0           balanced     cholesky   
1           balanced         auto   

                                              params  split0_test_score  \
0  {'class_weight': 'balanced', 'solver': 'choles...           0.946429   
1     {'class_weight': 'balanced', 'solver': 'auto'}           0.946429   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.964286              0.875           0.946429           0.945455   
1           0.964286              0.875           0.946429           0.945455   

   mean_test_score  std_test_score  rank_test_score  
0         0.935519         0.03107                1  
1         0.935519         0.03107                1

In [28]:
import pickle
filename=rootPath+"Deployed/CKD_RC_Grid.sav"
pickle.dump(grid,open(filename,'wb'))

In [29]:
loaded_model=pickle.load(open(filename,'rb'))
testdata=[[23,12,10,13,120,34,98,45,76,66,76,80,12,62,63,86,45,0,1,0,1,0,1,0,1,0,1]]
df=pd.DataFrame(testdata,columns=['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal','pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes','appet_yes', 'pe_yes', 'ane_yes'])
result=loaded_model.predict(df)
result

array([ True])