In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [34]:
rootPath = "../../../../../"
dataset=pd.read_csv(rootPath+"Datasets/CKD.csv")
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...      False        False       False   
1    137.528754  4.627244  10.700000  ...       True        False       False   
2    138.000000  4.400000  12.000000  ...       True        False       False   
3    138.000000  3.200000   8.100000  ...       True        False       False   
4    137.528754  4.627244  11.800000  ...       True        False       False   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...       True        False       False   
395  137.528754  4.627244   8.700000  ...       True        False       False   
396  134.000000  2.700000   9.100000  ...       True        False       False   
397  142.000000  5.500000   8.500000  ...       True        False       False   
398  140.000000  5.000000  16.300000  ...       True        False       False   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0      False   False    False       True    True    False                True  
1      False   False    False       True   False    False                True  
2      False   False    False       True   False    False                True  
3      False   False    False       True   False     True                True  
4      False   False    False       True   False    False                True  
..       ...     ...      ...        ...     ...      ...                 ...  
394    False   False    False       True   False    False                True  
395     True    True    False       True   False     True                True  
396     True    True    False      False   False    False                True  
397     True    True    False       True   False     True                True  
398    False   False    False       True   False    False               False  

[399 rows x 28 columns]

In [35]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [36]:
dataset["classification_yes"].value_counts()

classification_yes
True     249
False    150
Name: count, dtype: int64

In [37]:
independent=dataset[
    ['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv','wc',
     'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal','pcc_present',
       'ba_present', 'htn_yes', 'dm_yes', 'cad_yes','appet_yes','pe_yes', 'ane_yes']
]
dependent=dataset["classification_yes"]

In [38]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [39]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
param_grid={'criterion':['poisson','squared_error','gini','entropy'],'max_features':['auto','sqrt','log2']}
grid=GridSearchCV(DecisionTreeClassifier(),param_grid,refit=True,verbose=3,n_jobs=1)
grid.fit(X_train,y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV 1/5] END criterion=poisson, max_features=auto;, score=nan total time=   0.0s
[CV 2/5] END criterion=poisson, max_features=auto;, score=nan total time=   0.0s
[CV 3/5] END criterion=poisson, max_features=auto;, score=nan total time=   0.0s
[CV 4/5] END criterion=poisson, max_features=auto;, score=nan total time=   0.0s
[CV 5/5] END criterion=poisson, max_features=auto;, score=nan total time=   0.0s
[CV 1/5] END criterion=poisson, max_features=sqrt;, score=nan total time=   0.0s
[CV 2/5] END criterion=poisson, max_features=sqrt;, score=nan total time=   0.0s
[CV 3/5] END criterion=poisson, max_features=sqrt;, score=nan total time=   0.0s
[CV 4/5] END criterion=poisson, max_features=sqrt;, score=nan total time=   0.0s
[CV 5/5] END criterion=poisson, max_features=sqrt;, score=nan total time=   0.0s
[CV 1/5] END criterion=poisson, max_features=log2;, score=nan total time=   0.0s
[CV 2/5] END criterion=poisson, max_features=log

c:\Users\AraVinD\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
40 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\AraVinD\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\AraVinD\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "c:\Users\AraVinD\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\AraVinD\anaconda3\Lib\site

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=1,
             param_grid={'criterion': ['poisson', 'squared_error', 'gini',
                                       'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2']},
             verbose=3)

In [40]:
y_pred=grid.predict(X_test)
y_pred

array([False,  True, False, False,  True,  True,  True,  True, False,
       False,  True,  True, False,  True, False, False,  True, False,
        True,  True, False,  True,  True, False,  True, False, False,
       False,  True,  True,  True,  True, False, False, False, False,
       False, False,  True, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True, False,  True, False, False, False,  True,  True,
        True,  True,  True,  True, False, False, False,  True,  True,
       False,  True, False,  True,  True,  True,  True, False,  True,
        True, False, False,  True,  True, False,  True, False,  True,
        True,  True, False, False,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True, False,  True, False,  True,
       False,  True,  True, False,  True,  True,  True,  True,  True,
       False, False, False])

In [41]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9333333333333333

In [42]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[42,  3],
       [ 5, 70]], dtype=int64)

In [43]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)

In [44]:
print(clf_report)

              precision    recall  f1-score   support

       False       0.89      0.93      0.91        45
        True       0.96      0.93      0.95        75

    accuracy                           0.93       120
   macro avg       0.93      0.93      0.93       120
weighted avg       0.93      0.93      0.93       120



In [45]:
table=pd.DataFrame.from_dict(grid.cv_results_)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.001596  7.985480e-04         0.000000        0.000000   
1        0.001396  4.887928e-04         0.000000        0.000000   
2        0.001831  7.597786e-04         0.000000        0.000000   
3        0.001396  4.887936e-04         0.000000        0.000000   
4        0.001197  4.002572e-04         0.000000        0.000000   
5        0.001595  4.887141e-04         0.000000        0.000000   
6        0.001596  4.889479e-04         0.000000        0.000000   
7        0.003591  4.888698e-04         0.002393        0.000489   
8        0.003192  3.998051e-04         0.002502        0.000447   
9        0.001396  4.885777e-04         0.000000        0.000000   
10       0.002991  6.031566e-07         0.002704        0.000394   
11       0.002903  8.062294e-04         0.002394        0.000489   

   param_criterion param_max_features  \
0          poisson               auto   
1          poisson               sqrt   
2          poisson               log2   
3    squared_error               auto   
4    squared_error               sqrt   
5    squared_error               log2   
6             gini               auto   
7             gini               sqrt   
8             gini               log2   
9          entropy               auto   
10         entropy               sqrt   
11         entropy               log2   

                                               params  split0_test_score  \
0    {'criterion': 'poisson', 'max_features': 'auto'}                NaN   
1    {'criterion': 'poisson', 'max_features': 'sqrt'}                NaN   
2    {'criterion': 'poisson', 'max_features': 'log2'}                NaN   
3   {'criterion': 'squared_error', 'max_features':...                NaN   
4   {'criterion': 'squared_error', 'max_features':...                NaN   
5   {'criterion': 'squared_error', 'max_features':...                NaN   
6       {'criterion': 'gini', 'max_features': 'auto'}                NaN   
7       {'criterion': 'gini', 'max_features': 'sqrt'}           0.964286   
8       {'criterion': 'gini', 'max_features': 'log2'}           0.946429   
9    {'criterion': 'entropy', 'max_features': 'auto'}                NaN   
10   {'criterion': 'entropy', 'max_features': 'sqrt'}           0.946429   
11   {'criterion': 'entropy', 'max_features': 'log2'}           1.000000   

    split1_test_score  split2_test_score  split3_test_score  \
0                 NaN                NaN                NaN   
1                 NaN                NaN                NaN   
2                 NaN                NaN                NaN   
3                 NaN                NaN                NaN   
4                 NaN                NaN                NaN   
5                 NaN                NaN                NaN   
6                 NaN                NaN                NaN   
7            0.946429           0.946429           0.892857   
8            0.928571           0.892857           0.964286   
9                 NaN                NaN                NaN   
10           0.964286           0.928571           0.946429   
11           0.964286           0.910714           0.928571   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
0                 NaN              NaN             NaN                5  
1                 NaN              NaN             NaN                5  
2                 NaN              NaN             NaN                5  
3                 NaN              NaN             NaN                5  
4                 NaN              NaN             NaN                5  
5                 NaN              NaN             NaN                5  
6                 NaN              NaN             NaN                5  
7            0.963636         0.942727        0.026140                2  
8            0.927273         0.931883        0.023735                4  
9                 NaN              N

In [46]:
import pickle
filename=rootPath+"Deployed/CKD_DT_Grid.sav"
pickle.dump(grid,open(filename,'wb'))

In [47]:
loaded_model=pickle.load(open(filename,'rb'))
testdata=[[23,12,10,13,120,34,98,45,76,66,76,80,12,62,63,86,45,0,1,0,1,0,1,0,1,0,1]]
df=pd.DataFrame(testdata,columns=['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal','pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes','appet_yes', 'pe_yes', 'ane_yes'])
result=loaded_model.predict(df)
result

array([ True])