In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
rootPath = "../../../../../"
dataset=pd.read_csv(rootPath+"Datasets/CKD.csv")
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...      False        False       False   
1    137.528754  4.627244  10.700000  ...       True        False       False   
2    138.000000  4.400000  12.000000  ...       True        False       False   
3    138.000000  3.200000   8.100000  ...       True        False       False   
4    137.528754  4.627244  11.800000  ...       True        False       False   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...       True        False       False   
395  137.528754  4.627244   8.700000  ...       True        False       False   
396  134.000000  2.700000   9.100000  ...       True        False       False   
397  142.000000  5.500000   8.500000  ...       True        False       False   
398  140.000000  5.000000  16.300000  ...       True        False       False   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0      False   False    False       True    True    False                True  
1      False   False    False       True   False    False                True  
2      False   False    False       True   False    False                True  
3      False   False    False       True   False     True                True  
4      False   False    False       True   False    False                True  
..       ...     ...      ...        ...     ...      ...                 ...  
394    False   False    False       True   False    False                True  
395     True    True    False       True   False     True                True  
396     True    True    False      False   False    False                True  
397     True    True    False       True   False     True                True  
398    False   False    False       True   False    False               False  

[399 rows x 28 columns]

In [4]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [5]:
dataset["classification_yes"].value_counts()

classification_yes
True     249
False    150
Name: count, dtype: int64

In [6]:
independent=dataset[
    ['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv','wc',
     'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal','pcc_present',
       'ba_present', 'htn_yes', 'dm_yes', 'cad_yes','appet_yes','pe_yes', 'ane_yes']
]
dependent=dataset["classification_yes"]

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
param_grid={'kernel': ["linear", "rbf"],'C': [0.1,1]}#"poly","sigmoid"],'gamma':['auto','scale'], 'C':[10,100] ##including this makes this perform super slow. so excluded it via comments.
grid=GridSearchCV(SVC(probability=True,random_state=7,cache_size=1000),param_grid,scoring='r2',cv=5,refit=True,verbose=3,n_jobs=1)#,scoring='f1_weighted'
grid.fit(X_train,y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits
[CV 1/5] END ..............C=0.1, kernel=linear;, score=0.924 total time=  18.1s
[CV 2/5] END ..............C=0.1, kernel=linear;, score=0.848 total time=  26.8s
[CV 3/5] END ..............C=0.1, kernel=linear;, score=0.924 total time=  15.7s
[CV 4/5] END ..............C=0.1, kernel=linear;, score=0.771 total time=  13.9s
[CV 5/5] END ..............C=0.1, kernel=linear;, score=0.846 total time=  46.8s
[CV 1/5] END ................C=0.1, kernel=rbf;, score=-0.600 total time=   0.0s
[CV 2/5] END ................C=0.1, kernel=rbf;, score=-0.600 total time=   0.0s
[CV 3/5] END ................C=0.1, kernel=rbf;, score=-0.600 total time=   0.0s
[CV 4/5] END ................C=0.1, kernel=rbf;, score=-0.600 total time=   0.0s
[CV 5/5] END ................C=0.1, kernel=rbf;, score=-0.618 total time=   0.0s
[CV 1/5] END ................C=1, kernel=linear;, score=1.000 total time=  38.7s
[CV 2/5] END ................C=1, kernel=linear;,

GridSearchCV(cv=5,
             estimator=SVC(cache_size=1000, probability=True, random_state=7),
             n_jobs=1, param_grid={'C': [0.1, 1], 'kernel': ['linear', 'rbf']},
             scoring='r2', verbose=3)

In [9]:
print("Best parameters found:",grid.best_params_)
print("Best cross-validation score:",grid.best_score_)

Best parameters found: {'C': 0.1, 'kernel': 'linear'}
Best cross-validation score: 0.8625210084033613


In [10]:
#results_df = pd.DataFrame(grid.cv_results_)
#print(results_df)
#print(results_df[['params', 'mean_test_score', 'std_test_score', 'rank_test_score']])
table=pd.DataFrame.from_dict(grid.cv_results_)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0      24.367712     12.108620         0.002198        0.000398      0.1   
1       0.013218      0.000401         0.003193        0.000398      0.1   
2      34.828580     14.628206         0.002554        0.000763      1.0   
3       0.013486      0.000687         0.003708        0.000819      1.0   

  param_kernel                          params  split0_test_score  \
0       linear  {'C': 0.1, 'kernel': 'linear'}            0.92381   
1          rbf     {'C': 0.1, 'kernel': 'rbf'}           -0.60000   
2       linear    {'C': 1, 'kernel': 'linear'}            1.00000   
3          rbf       {'C': 1, 'kernel': 'rbf'}           -0.60000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.847619           0.923810           0.771429           0.845938   
1          -0.600000          -0.600000          -0.600000          -0.617647   
2           0.695238           0.771429           0.771429           0.845938   
3          -0.600000          -0.600000          -0.600000          -0.617647   

   mean_test_score  std_test_score  rank_test_score  
0         0.862521        0.057109                1  
1        -0.603529        0.007059                3  
2         0.816807        0.103253                2  
3        -0.603529        0.007059                3

In [11]:
y_pred=grid.predict(X_test)
y_pred

array([False,  True, False,  True,  True,  True,  True,  True, False,
       False,  True,  True, False,  True, False, False,  True, False,
        True,  True, False,  True,  True, False,  True, False, False,
       False,  True,  True,  True,  True, False, False, False, False,
       False, False,  True, False, False,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True, False,
        True,  True, False,  True, False, False, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
       False, False, False,  True,  True,  True,  True, False,  True,
        True, False, False,  True,  True, False,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True, False,  True, False,  True,
       False,  True,  True, False,  True,  True,  True,  True,  True,
       False, False, False])

In [12]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9988148148148148

In [13]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[44  1]
 [ 0 75]]


In [14]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)

In [15]:
print (clf_report)

              precision    recall  f1-score   support

       False       1.00      0.98      0.99        45
        True       0.99      1.00      0.99        75

    accuracy                           0.99       120
   macro avg       0.99      0.99      0.99       120
weighted avg       0.99      0.99      0.99       120



In [16]:
re=grid.cv_results_
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0      24.367712     12.108620         0.002198        0.000398      0.1   
1       0.013218      0.000401         0.003193        0.000398      0.1   
2      34.828580     14.628206         0.002554        0.000763      1.0   
3       0.013486      0.000687         0.003708        0.000819      1.0   

  param_kernel                          params  split0_test_score  \
0       linear  {'C': 0.1, 'kernel': 'linear'}            0.92381   
1          rbf     {'C': 0.1, 'kernel': 'rbf'}           -0.60000   
2       linear    {'C': 1, 'kernel': 'linear'}            1.00000   
3          rbf       {'C': 1, 'kernel': 'rbf'}           -0.60000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.847619           0.923810           0.771429           0.845938   
1          -0.600000          -0.600000          -0.600000          -0.617647   
2           0.695238           0.771429           0.771429           0.845938   
3          -0.600000          -0.600000          -0.600000          -0.617647   

   mean_test_score  std_test_score  rank_test_score  
0         0.862521        0.057109                1  
1        -0.603529        0.007059                3  
2         0.816807        0.103253                2  
3        -0.603529        0.007059                3

In [17]:
import pickle
filename=rootPath+"Deployed/CKD_SVM_Grid.sav"
pickle.dump(grid,open(filename,'wb'))

In [18]:
loaded_model=pickle.load(open(filename,'rb'))
testdata=[[23,12,10,13,120,34,98,45,76,66,76,80,12,62,63,86,45,0,1,0,1,0,1,0,1,0,1]]
df=pd.DataFrame(testdata,columns=['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal','pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes','appet_yes', 'pe_yes', 'ane_yes'])
result=loaded_model.predict(df)
result

array([ True])